const words = [
    { "name": "full-range", "value": 27 },
    { "name": "methodology", "value": 78 },
    { "name": "Intuitive", "value": 18 },
    { "name": "User-centric", "value": 98 },
    { "name": "intranet", "value": 33 },
    { "name": "grid-enabled", "value": 52 },
    { "name": "definition", "value": 12 },
    { "name": "Switchable", "value": 85 },
    { "name": "secured line", "value": 26 },
    { "name": "Versatile", "value": 78 },
    { "name": "methodical", "value": 10 },
    { "name": "firmware", "value": 69 },
    { "name": "upward-trending", "value": 68 },
    { "name": "executive", "value": 52 },
    { "name": "Implemented", "value": 62 },
    { "name": "User-friendly", "value": 42 },
    { "name": "asynchronous", "value": 22 },
    { "name": "system-worthy", "value": 27 },
    { "name": "artificial intelligence", "value": 53 },
    { "name": "Phased", "value": 87 },
    { "name": "Organic", "value": 38 },
    { "name": "explicit", "value": 38 },
    { "name": "Organized", "value": 67 },
    { "name": "collaboration", "value": 22 },
    { "name": "Assimilated", "value": 24 },
    { "name": "heuristic", "value": 19 },
    { "name": "responsive", "value": 94 },
    { "name": "multi-tasking", "value": 16 },
    { "name": "Mandatory", "value": 83 },
    { "name": "encompassing", "value": 86 },
    { "name": "Face to face", "value": 19 },
    { "name": "Multi-layered", "value": 75 },
    { "name": "foreground", "value": 20 },
    { "name": "eco-centric", "value": 19 },
    { "name": "Diverse", "value": 72 },
    { "name": "strategy", "value": 47 },
    { "name": "stable", "value": 97 },
    { "name": "Adaptive", "value": 74 },
    { "name": "Open-source", "value": 19 },
    { "name": "Cross-group", "value": 17 },
    { "name": "Implemented", "value": 80 },
    { "name": "Persevering", "value": 86 },
    { "name": "interactive", "value": 30 },
    { "name": "emulation", "value": 58 },
    { "name": "analyzer", "value": 18 },
    { "name": "actuating", "value": 4 },
    { "name": "Re-engineered", "value": 88 },
    { "name": "Cloned", "value": 4 },
    { "name": "Customer-focused", "value": 57 },
    { "name": "context-sensitive", "value": 52 },
    { "name": "success", "value": 33 },
    { "name": "migration", "value": 99 },
    { "name": "info-mediaries", "value": 96 },
    { "name": "Cloned", "value": 20 },
    { "name": "Cloned", "value": 59 },
    { "name": "benchmark", "value": 20 },
    { "name": "knowledge user", "value": 37 },
    { "name": "adapter", "value": 10 },
    { "name": "leading edge", "value": 68 },
    { "name": "Polarised", "value": 5 },
    { "name": "open architecture", "value": 9 },
    { "name": "real-time", "value": 16 },
    { "name": "local area network", "value": 96 },
    { "name": "non-volatile", "value": 79 },
    { "name": "help-desk", "value": 49 },
    { "name": "multi-tasking", "value": 23 },
    { "name": "model", "value": 73 },
    { "name": "Managed", "value": 87 },
    { "name": "flexibility", "value": 4 },
    { "name": "dynamic", "value": 47 },
    { "name": "Configurable", "value": 18 },
    { "name": "real-time", "value": 1 },
    { "name": "executive", "value": 25 },
    { "name": "zero defect", "value": 90 },
    { "name": "interactive", "value": 89 },
    { "name": "heuristic", "value": 55 },
    { "name": "clear-thinking", "value": 50 },
    { "name": "Organic", "value": 69 },
    { "name": "mobile", "value": 88 },
    { "name": "core", "value": 15 },
    { "name": "Organic", "value": 24 },
    { "name": "intermediate", "value": 19 },
    { "name": "matrix", "value": 96 },
    { "name": "policy", "value": 17 },
    { "name": "Proactive", "value": 97 },
    { "name": "Persistent", "value": 83 },
    { "name": "orchestration", "value": 57 },
    { "name": "complexity", "value": 56 },
    { "name": "neutral", "value": 93 },
    { "name": "orchestration", "value": 42 },
    { "name": "modular", "value": 44 },
    { "name": "contingency", "value": 43 },
    { "name": "Implemented", "value": 35 },
    { "name": "intermediate", "value": 87 },
    { "name": "tangible", "value": 79 },
    { "name": "hierarchy", "value": 79 },
    { "name": "Profound", "value": 7 },
    { "name": "Total", "value": 6 },
    { "name": "strategy", "value": 63 },

    { "name": "portal", "value": 11 },
    { "name": "function", "value": 2 },
    { "name": "even-keeled", "value": 86 },
    { "name": "system-worthy", "value": 65 },
    { "name": "stable", "value": 47 },
    { "name": "Integrated", "value": 31 },
    { "name": "high-level", "value": 70 },
    { "name": "help-desk", "value": 10 },
    { "name": "concept", "value": 47 },
    { "name": "real-time", "value": 35 },
    { "name": "radical", "value": 28 },
    { "name": "solution-oriented", "value": 31 },
    { "name": "Phased", "value": 21 },
    { "name": "forecast", "value": 82 },
    { "name": "Reverse-engineered", "value": 71 },
    { "name": "Secured", "value": 83 },
    { "name": "time-frame", "value": 11 },
    { "name": "Versatile", "value": 26 },
    { "name": "background", "value": 18 },
    { "name": "neural-net", "value": 32 },
    { "name": "support", "value": 51 },
    { "name": "local area network", "value": 100 },
    { "name": "paradigm", "value": 37 },
    { "name": "explicit", "value": 69 },
    { "name": "Compatible", "value": 89 },
    { "name": "impactful", "value": 58 },
    { "name": "holistic", "value": 80 },
    { "name": "Re-contextualized", "value": 28 },
    { "name": "Extended", "value": 41 },
    { "name": "Graphical User Interface", "value": 89 },
    { "name": "Extended", "value": 88 },
    { "name": "flexibility", "value": 80 },
    { "name": "Centralized", "value": 10 },
    { "name": "Open-architected", "value": 66 },
    { "name": "web-enabled", "value": 10 },
    { "name": "reciprocal", "value": 67 },
    { "name": "non-volatile", "value": 72 },
    { "name": "budgetary management", "value": 20 },
    { "name": "zero tolerance", "value": 64 },
    { "name": "hierarchy", "value": 19 },
    { "name": "Open-architected", "value": 31 },
    { "name": "User-centric", "value": 44 },
    { "name": "high-level", "value": 42 },
    { "name": "throughput", "value": 53 }
];

// const lol = d3.layout.cloud(words);
const svg = d3
    .select("svg")
    .attr("text-anchor", "middle")
    .attr("height", 800)
    .attr("width", 800)
    // .append("g")
const fontSize = d3.scalePow().exponent(5).domain([0, 1]).range([10, 40]);
const cloud = d3.layout.cloud()
    .size([800, 800])
    .words(words)
    // .padding(0)
    // .rotate(0)
    // .font('Impact')
    .fontSize(function (d, i) { return fontSize(Math.random()); })
    .on("word", ({ size, x, y, rotate, name }) => {
        svg.append("text")
            .attr("font-size", size)
            .attr("x", x)
            .attr("y", y)
            // .attr("transform", `translate(${x},${y}) rotate(${rotate})`)
            .attr("fill", "black")
            .text(name);
    })
    .on("end", console.log)

cloud.start();