@startmindmap
* Methode de travail en informatique (langage)

** Fa nanina nanao informatique
*** Vola
*** Otrn hoe mora ilay izy
*** Satria te hanao multimedia
*** Passion

** Raha te hianatra info moa izany dia inona ny toetra tokony hanana
*** Tia mianatra, tia mikaroka, Perfectioniste ary autodidacte
**** Evolution technologie
**** Solution optimale
**** Style code 
**** Solution optimale
*** Tia manandrana (pratique)
**** Tsy possible ny mahay raha tsy mipratique (exemple mpandrafitra)
*** Mahay mamaky teny ary mahay misitona mot clé (mi-google)
**** Mi-comprendre teny anglisy
**** Ideale: Afaka mihaino teny anglisy
*** Tsy mora kivy de tsy miabandonne
*** Tia manao enquete, Manaraka trace-na zvt

** Inona daholo ireo zavatra ahafahana mianatra
*** Tuto Youtube
**** Fort
***** Ideale raha te hianatra zvt specifique
***** Mety koa raha hijerena globalement zavatra iray
***** Be dia be
***** Gratuit

**** Faible 
***** Lasa mpanao saisie(copie collé)
***** Tsy ahaizana zvt generique
***** Sarotra be ny mijery fonction specifique na zvt specifique tiana ho jerena

*** Formation Elephorm Video2brain udemy, Livre (PDF)

**** Fort
***** Ideale raha vao manomboka
***** Complet kokoa noho ny tuto Youtube
***** Nandalo etape de validation fa tsy izay te hanao de manao azy donc Tsara kokoa ny qualité 

**** Faible 
***** Sarotra be ny mijery fonction specifique na zvt specifique tiana ho jerena
***** Lasa mpanao saisie(copie collé)
***** Lent be mianatra azy

*** Olona mampianatra
**** Fort
***** Ideale raha mianatra concept vaovao
***** Ideale raha ifampizarana experiences
***** Ideale raha hanontaniana hoe raha hanao zvt otran zao de inona no tokony ho hay

**** Faible 
***** Lasa dependant anle olona de tsy autonome tsony
***** Ny olona tsy disponible foana sady mety reraka rf hanontaniana foana

*** Documentation
**** Fort
***** Ideale raha efa mahay anle concept de base
***** Mora ny mitady fonction specifique na zvt specifique
***** Mazava tsara ny fampiasana anle zvt

**** Faible 
***** Misy fotoana somary sarotra mamaky azy
***** Dray2 izy incomplet (open source, sous documenté)

*** Google, Stackoverflow, Baedung, Quora...
**** Fort
***** Hita ao dol ny rht (99,99%)
***** Be dia be ny solution ary detaillé

**** Faible
***** Lasa mpanao saisie (copie collé)
***** Vao misy probleme de google nefa mety probleme simple kely
***** Lasa mahatonga an olona kamo hieritreritra

** Fomba fianarako
*** Concepts 
**** Youtube, Formation, Livre, Documentation officielle, Cheat sheet
*** Pratique
**** 1- Documentation officielle
**** 2- Erreur
**** 3- Google

** Erreur debutant
*** Manenjika note ftsn fa tsy mianatra mba ahay
*** Miankina be amin'ny editeur
*** Tsy tia mianatra theorie, Paradigme, Concepts...
*** Manoratra code na de tsy azo ary izay zavatra soratana
*** Manoratra vao Mieritreritra
*** Manaraka tuto betement Tsy misy comprehension
*** Mamaky PDF iray manontolo izay vao manao pratique
*** Manao copie collé solution magique avy any @google
*** Mieritreritra hoe rf mandeha ny code de ampy izay
*** Tsy mirarah endrika-na code
*** Manao code tsis mahazo mba hoe za rery ihany no afaka manao modif anle code
*** Mampiasa commentaire be loatra

@endmindmap